package com.amazon.common.util;

public class AmzOrderMutations {
	public static final String AMZ_GET_ORDER_QUERY = "query order($orderIdentifier: OrderIdentifierInput!) {\r\n"
			+ "  order(orderIdentifier: $orderIdentifier) {\r\n"
			+ "    id\r\n"
			+ "    metadata {\r\n"
			+ "      executionState\r\n"
			+ "    }\r\n"
			+ "    customer {\r\n"
			+ "      contact {\r\n"
			+ "        id\r\n"
			+ "        name\r\n"
			+ "        email\r\n"
			+ "      }\r\n"
			+ "    }\r\n"
			+ "    packageInformation {\r\n"
			+ "      summary {\r\n"
			+ "        state\r\n"
			+ "      }\r\n"
			+ "      details {\r\n"
			+ "        id\r\n"
			+ "        state\r\n"
			+ "        reason\r\n"
			+ "        packageInformationDetailsFor {\r\n"
			+ "          orderLineItems {\r\n"
			+ "            lineItem {\r\n"
			+ "              id\r\n"
			+ "            }\r\n"
			+ "            amount {\r\n"
			+ "              unit\r\n"
			+ "              value\r\n"
			+ "            }\r\n"
			+ "            \r\n"
			+ "          }\r\n"
			+ "        }\r\n"
			+ "        packageTracker {\r\n"
			+ "          packageTrackerIdentifier {\r\n"
			+ "            trackingNumber\r\n"
			+ "            carrierCode\r\n"
			+ "          }\r\n"
			+ "          latestMilestone {\r\n"
			+ "            status {\r\n"
			+ "              code\r\n"
			+ "            }\r\n"
			+ "          }\r\n"
			+ "        }\r\n"
			+ "      }\r\n"
			+ "    }\r\n"
			+ "    returns {\r\n"
			+ "      details {\r\n"
			+ "        id\r\n"
			+ "        state\r\n"
			+ "        returnDeliveryDetails {\r\n"
			+ "          id\r\n"
			+ "          state\r\n"
			+ "          returnDeliveryFor {\r\n"
			+ "            orderLineItemAmounts {\r\n"
			+ "              amount {\r\n"
			+ "                unit\r\n"
			+ "                value\r\n"
			+ "              }\r\n"
			+ "              lineItem {\r\n"
			+ "                id\r\n"
			+ "              }\r\n"
			+ "            }\r\n"
			+ "          }\r\n"
			+ "        }\r\n"
			+ "        returnLineItems {\r\n"
			+ "          id\r\n"
			+ "          grading {\r\n"
			+ "            summary {\r\n"
			+ "              gradedAmount {\r\n"
			+ "                unit\r\n"
			+ "                value\r\n"
			+ "              }\r\n"
			+ "              unitWiseCondition {\r\n"
			+ "                amount {\r\n"
			+ "                  unit\r\n"
			+ "                  value\r\n"
			+ "                }\r\n"
			+ "                condition\r\n"
			+ "              }\r\n"
			+ "            }\r\n"
			+ "          }\r\n"
			+ "        }\r\n"
			+ "      }\r\n"
			+ "    }\r\n"
			+ "    lineItems {\r\n"
			+ "      id\r\n"
			+ "      amount {\r\n"
			+ "        unit\r\n"
			+ "        value\r\n"
			+ "      }\r\n"
			+ "      product {\r\n"
			+ "        productId {\r\n"
			+ "          value\r\n"
			+ "        }\r\n"
			+ "        title\r\n"
			+ "        productDetailPageUrl\r\n"
			+ "        image {\r\n"
			+ "          displayReadyUrl\r\n"
			+ "          sourceUrl\r\n"
			+ "          altText\r\n"
			+ "        }\r\n"
			+ "        price {\r\n"
			+ "          currencyCode\r\n"
			+ "          amount\r\n"
			+ "        }\r\n"
			+ "        variationSelections {\r\n"
			+ "          dimension\r\n"
			+ "          value\r\n"
			+ "        }\r\n"
			+ "      }\r\n"
			+ "	  aliases {\r\n"
			+ "        \r\n"
			+ "            aliasId\r\n"
			+ "            aliasType\r\n"
			+ "        \r\n"
			+ "      }\r\n"
			+ "    }\r\n"
			+ "    totalPrice {\r\n"
			+ "      value {\r\n"
			+ "        amount\r\n"
			+ "        currencyCode\r\n"
			+ "      }\r\n"
			+ "    }\r\n"
			+ "  }\r\n"
			+ "}\r\n"
			+ "";
	
	public static final String AMZ_GET_ORDER_FOR_EXECUTION_STATE_QUERY ="query order($orderIdentifier: OrderIdentifierInput!) {\r\n"
			+ "  order(orderIdentifier: $orderIdentifier) {\r\n"
			+ "    id\r\n"
			+ "    metadata {\r\n"
			+ "      executionState\r\n"
			+ "    }\r\n"
			+ "  }\r\n"
			+ "}\r\n"
			+ "";

	public static final String AMZ_UPDATE_ORDER_FOR_EXECUTION_STATE_QUERY = "mutation updateOrder($orderIdentifier: OrderIdentifierInput!, $input: UpdateOrderInput!) {\r\n"
			+ "    updateOrder(orderIdentifier: $orderIdentifier, input: $input) {\r\n"
			+ "        order {\r\n"
			+ "          id\r\n"
			+ "        }\r\n"
			+ "    }\r\n"
			+ "}";
	
	public static final String AMZ_CREATE_ORDER_QUERY = "mutation createOrder($input: CreateOrderInput!) {\r\n"
			+ "  createOrder(input: $input) {\r\n"
			+ "    order {\r\n"
			+ "      id\r\n"
			+ "      orderLinks {\r\n"
			+ "        destinationType\r\n"
			+ "        url\r\n"
			+ "      }\r\n"
			+ "    }\r\n"
			+ "  }\r\n"
			+ "}\r\n"
			+ "";
	
	public static final String AMZ_COMPLETE_ORDER_DETAILS ="query order($orderIdentifier: OrderIdentifierInput!) {\r\n"
			+ "  order(orderIdentifier: $orderIdentifier) {\r\n"
			+ "    id\r\n"
			+ "    metadata {\r\n"
			+ "      executionState\r\n"
			+ "    }\r\n"
			+ "    customer {\r\n"
			+ "      contact {\r\n"
			+ "        id\r\n"
			+ "        name\r\n"
			+ "        email\r\n"
			+ "      }\r\n"
			+ "    }\r\n"
			+ "    packageInformation {\r\n"
			+ "      summary {\r\n"
			+ "        state\r\n"
			+ "      }\r\n"
			+ "      details {\r\n"
			+ "        id\r\n"
			+ "        state\r\n"
			+ "        reason\r\n"
			+ "        packageInformationDetailsFor {\r\n"
			+ "          orderLineItems {\r\n"
			+ "            lineItem {\r\n"
			+ "              id\r\n"
			+ "            }\r\n"
			+ "            amount {\r\n"
			+ "              unit\r\n"
			+ "              value\r\n"
			+ "            }\r\n"
			+ "          }\r\n"
			+ "        }\r\n"
			+ "        packageTracker {\r\n"
			+ "          trackingUrl\r\n"
			+ "          packageTrackerIdentifier {\r\n"
			+ "            trackingNumber\r\n"
			+ "            carrierCode\r\n"
			+ "          }\r\n"
			+ "          latestMilestone {\r\n"
			+ "            status {\r\n"
			+ "              code\r\n"
			+ "            }\r\n"
			+ "          }\r\n"
			+ "          milestones {\r\n"
			+ "            status {\r\n"
			+ "              code\r\n"
			+ "              message {\r\n"
			+ "                locale\r\n"
			+ "                value\r\n"
			+ "              }\r\n"
			+ "            }\r\n"
			+ "            occurredAt\r\n"
			+ "          }\r\n"
			+ "        }\r\n"
			+ "      }\r\n"
			+ "    }\r\n"
			+ "    returns {\r\n"
			+ "      details {\r\n"
			+ "        aliases {\r\n"
			+ "          aliasId\r\n"
			+ "          aliasType\r\n"
			+ "        }\r\n"
			+ "        id\r\n"
			+ "        returnFor {\r\n"
			+ "          orderLineItemAmounts {\r\n"
			+ "            lineItem {\r\n"
			+ "              id\r\n"
			+ "            }\r\n"
			+ "            amount {\r\n"
			+ "              value\r\n"
			+ "            }\r\n"
			+ "          }\r\n"
			+ "        }\r\n"
			+ "        state\r\n"
			+ "        returnDeliveryDetails {\r\n"
			+ "          id\r\n"
			+ "          state\r\n"
			+ "          returnDeliveryFor {\r\n"
			+ "            orderLineItemAmounts {\r\n"
			+ "              amount {\r\n"
			+ "                unit\r\n"
			+ "                value\r\n"
			+ "              }\r\n"
			+ "              lineItem {\r\n"
			+ "                id\r\n"
			+ "              }\r\n"
			+ "            }\r\n"
			+ "          }\r\n"
			+ "        }\r\n"
			+ "        returnLineItems {\r\n"
			+ "          id\r\n"
			+ "          refundDetails {\r\n"
			+ "            id\r\n"
			+ "          }\r\n"
			+ "          returnFor {\r\n"
			+ "            orderLineItemAmounts {\r\n"
			+ "              lineItem {\r\n"
			+ "                id\r\n"
			+ "              }\r\n"
			+ "              amount {\r\n"
			+ "                value\r\n"
			+ "              }\r\n"
			+ "            }\r\n"
			+ "          }\r\n"
			+ "\r\n"
			+ "          returnReason {\r\n"
			+ "            reasonCode\r\n"
			+ "          }\r\n"
			+ "          grading {\r\n"
			+ "            summary {\r\n"
			+ "              gradedAmount {\r\n"
			+ "                unit\r\n"
			+ "                value\r\n"
			+ "              }\r\n"
			+ "              unitWiseCondition {\r\n"
			+ "                amount {\r\n"
			+ "                  unit\r\n"
			+ "                  value\r\n"
			+ "                }\r\n"
			+ "                condition\r\n"
			+ "              }\r\n"
			+ "            }\r\n"
			+ "          }\r\n"
			+ "        }\r\n"
			+ "      }\r\n"
			+ "    }\r\n"
			+ "    refunds {\r\n"
			+ "      details {\r\n"
			+ "        aliases {\r\n"
			+ "          aliasId\r\n"
			+ "          aliasType\r\n"
			+ "        }\r\n"
			+ "        id\r\n"
			+ "        updatedAt\r\n"
			+ "        state\r\n"
			+ "        refundRequestReason\r\n"
			+ "        refundTotal {\r\n"
			+ "          totalAmount {\r\n"
			+ "            amount\r\n"
			+ "          }\r\n"
			+ "        }\r\n"
			+ "        refundFor {\r\n"
			+ "			causedBy{\r\n"
			+ "                id\r\n"
			+ "            }\r\n"
			+ "          orderLineItems {\r\n"
			+ "            lineItem {\r\n"
			+ "              id\r\n"
			+ "            }\r\n"
			+ "            amount {\r\n"
			+ "              unit\r\n"
			+ "              value\r\n"
			+ "            }\r\n"
			+ "          }\r\n"
			+ "        }\r\n"
			+ "      }\r\n"
			+ "    }\r\n"
			+ "    lineItems {\r\n"
			+ "      id\r\n"
			+ "      amount {\r\n"
			+ "        unit\r\n"
			+ "        value\r\n"
			+ "      }\r\n"
			+ "      product {\r\n"
			+ "        productId {\r\n"
			+ "          value\r\n"
			+ "        }\r\n"
			+ "        title\r\n"
			+ "        productDetailPageUrl\r\n"
			+ "        image {\r\n"
			+ "          displayReadyUrl\r\n"
			+ "          sourceUrl\r\n"
			+ "          altText\r\n"
			+ "        }\r\n"
			+ "        price {\r\n"
			+ "          currencyCode\r\n"
			+ "          amount\r\n"
			+ "        }\r\n"
			+ "        variationSelections {\r\n"
			+ "          dimension\r\n"
			+ "          value\r\n"
			+ "        }\r\n"
			+ "      }\r\n"
			+ "      aliases {\r\n"
			+ "        aliasId\r\n"
			+ "        aliasType\r\n"
			+ "      }\r\n"
			+ "    }\r\n"
			+ "    totalPrice {\r\n"
			+ "      value {\r\n"
			+ "        amount\r\n"
			+ "        currencyCode\r\n"
			+ "      }\r\n"
			+ "    }\r\n"
			+ "  }\r\n"
			+ "}\r\n"
			+ "";
	
	public static final String AMZ_GET_INENTORY_ITEM ="query inventoryItem($id: String!) {\r\n"
			+ "  inventoryItem(inventoryItemId: $id) {\r\n"
			+ "	inventoryItemId    \r\n"
			+ "	buyableQuantity {      \r\n"
			+ "		unit      \r\n"
			+ "		amount\r\n"
			+ "	}    \r\n"
			+ "	product {      \r\n"
			+ "		amazonSku {        \r\n"
			+ "			value\r\n"
			+ "		    marketplaceId      \r\n"
			+ "		}\r\n"
			+ "         externalId {\r\n"
			+ "            value\r\n"
			+ "          }\r\n"
			+ "          sku {\r\n"
			+ "            value\r\n"
			+ "          }\r\n"
			+ "    \r\n"
			+ "	}  \r\n"
			+ "  }\r\n"
			+ "}";
	
	public static final String AMZ_GET_PRODUCT = "query product($identifier: ProductIdentifierInput) {\r\n"
			+ "  product(identifier: $identifier) {\r\n"
			+ "    id\r\n"
			+ "    externalId {\r\n"
			+ "      value\r\n"
			+ "    }\r\n"
			+ "    sku {\r\n"
			+ "      value\r\n"
			+ "    }\r\n"
			+ "    amazonSku {\r\n"
			+ "      value\r\n"
			+ "    }  \r\n"
			+ "    buyability {\r\n"
			+ "      status\r\n"
			+ "    }\r\n"
			+ "    inventoryItem {\r\n"
			+ "      inventoryItemId\r\n"
			+ "      buyableQuantity {\r\n"
			+ "        amount\r\n"
			+ "        unit\r\n"
			+ "      }\r\n"
			+ "    }\r\n"
			+ "  }\r\n"
			+ "}\r\n"
			+ "";
			
				public static final String AMZ_GET_REFUND_ORDER_DETAILS ="query order($orderIdentifier: OrderIdentifierInput!) {\r\n"
						+ "  order(orderIdentifier: $orderIdentifier) {\r\n"
						+ "    id\r\n"
						+ "    orderLinks {\r\n"
						+ "      destinationType\r\n"
						+ "      url\r\n"
						+ "    }\r\n"
						+ "    customer {\r\n"
						+ "      contact {\r\n"
						+ "        id\r\n"
						+ "        name\r\n"
						+ "        email\r\n"
						+ "      }\r\n"
						+ "    }\r\n"
						+ "    metadata {\r\n"
						+ "      executionState\r\n"
						+ "    }\r\n"
						+ "    returns {\r\n"
						+ "      details {\r\n"
						+ "        id\r\n"
						+ "        state\r\n"
						+ "        returnLineItems {\r\n"
						+ "          id\r\n"
						+ "          grading {\r\n"
						+ "            summary {\r\n"
						+ "              gradedAmount {\r\n"
						+ "                unit\r\n"
						+ "              }\r\n"
						+ "              unitWiseCondition {\r\n"
						+ "                condition\r\n"
						+ "                amount {\r\n"
						+ "                  unit\r\n"
						+ "                }\r\n"
						+ "              }\r\n"
						+ "            }\r\n"
						+ "          }\r\n"
						+ "        }\r\n"
						+ "        returnDeliveryDetails {\r\n"
						+ "          id\r\n"
						+ "          state\r\n"
						+ "          reason\r\n"
						+ "          returnDeliveryFor {\r\n"
						+ "            orderLineItemAmounts {\r\n"
						+ "              lineItem {\r\n"
						+ "                id\r\n"
						+ "              }\r\n"
						+ "              amount {\r\n"
						+ "                unit\r\n"
						+ "                value\r\n"
						+ "              }\r\n"
						+ "            }\r\n"
						+ "          }\r\n"
						+ "        }\r\n"
						+ "      }\r\n"
						+ "    }\r\n"
						+ "    packageInformation {\r\n"
						+ "      summary {\r\n"
						+ "        state\r\n"
						+ "      }\r\n"
						+ "      details {\r\n"
						+ "        id\r\n"
						+ "        state\r\n"
						+ "        reason\r\n"
						+ "        packageTracker {\r\n"
						+ "          packageTrackerIdentifier {\r\n"
						+ "            trackingNumber\r\n"
						+ "            carrierCode\r\n"
						+ "          }\r\n"
						+ "          latestMilestone {\r\n"
						+ "            status {\r\n"
						+ "              code\r\n"
						+ "            }\r\n"
						+ "          }\r\n"
						+ "        }\r\n"
						+ "        packageInformationDetailsFor {\r\n"
						+ "          orderLineItems {\r\n"
						+ "            lineItem {\r\n"
						+ "              id\r\n"
						+ "            }\r\n"
						+ "            amount {\r\n"
						+ "              unit\r\n"
						+ "              value\r\n"
						+ "            }\r\n"
						+ "          }\r\n"
						+ "        }\r\n"
						+ "      }\r\n"
						+ "    }\r\n"
						+ "    lineItems {\r\n"
						+ "      id\r\n"
						+ "      amount {\r\n"
						+ "        unit\r\n"
						+ "        value\r\n"
						+ "      }\r\n"
						+ "      product {\r\n"
						+ "        offerPrime\r\n"
						+ "        productId {\r\n"
						+ "          value\r\n"
						+ "        }\r\n"
						+ "        title\r\n"
						+ "        productDetailPageUrl\r\n"
						+ "        image {\r\n"
						+ "          displayReadyUrl\r\n"
						+ "          sourceUrl\r\n"
						+ "          altText\r\n"
						+ "        }\r\n"
						+ "        price {\r\n"
						+ "          currencyCode\r\n"
						+ "          amount\r\n"
						+ "        }\r\n"
						+ "        variationSelections {\r\n"
						+ "          dimension\r\n"
						+ "          value\r\n"
						+ "        }\r\n"
						+ "      }\r\n"
						+ "      deliveryOffer {\r\n"
						+ "        details {\r\n"
						+ "          deliveryPreviewId\r\n"
						+ "          id\r\n"
						+ "          deliveryProvider\r\n"
						+ "          deliveryTerms {\r\n"
						+ "            isPrimeEligible\r\n"
						+ "          }\r\n"
						+ "          taxes {\r\n"
						+ "            summary {\r\n"
						+ "              collectableTaxAmount {\r\n"
						+ "                amount\r\n"
						+ "                currencyCode\r\n"
						+ "              }\r\n"
						+ "            }\r\n"
						+ "          }\r\n"
						+ "          discounts {\r\n"
						+ "            details {\r\n"
						+ "              amount {\r\n"
						+ "                amount\r\n"
						+ "                currencyCode\r\n"
						+ "              }\r\n"
						+ "              couponCode\r\n"
						+ "              aliases {\r\n"
						+ "                aliasType\r\n"
						+ "              }\r\n"
						+ "              displayString\r\n"
						+ "            }\r\n"
						+ "          }\r\n"
						+ "        }\r\n"
						+ "      }\r\n"
						+ "      taxes {\r\n"
						+ "        summary {\r\n"
						+ "          collectableTaxAmount {\r\n"
						+ "            amount\r\n"
						+ "            currencyCode\r\n"
						+ "          }\r\n"
						+ "        }\r\n"
						+ "      }\r\n"
						+ "      discounts {\r\n"
						+ "        summary {\r\n"
						+ "          amount {\r\n"
						+ "            amount\r\n"
						+ "            currencyCode\r\n"
						+ "          }\r\n"
						+ "        }\r\n"
						+ "      }\r\n"
						+ "      payments {\r\n"
						+ "        summary {\r\n"
						+ "          amount {\r\n"
						+ "            amount\r\n"
						+ "          }\r\n"
						+ "          paymentMethodDisplayString\r\n"
						+ "          state\r\n"
						+ "        }\r\n"
						+ "      }\r\n"
						+ "    }\r\n"
						+ "    taxes {\r\n"
						+ "      summary {\r\n"
						+ "        collectableTaxAmount {\r\n"
						+ "          amount\r\n"
						+ "          currencyCode\r\n"
						+ "        }\r\n"
						+ "      }\r\n"
						+ "    }\r\n"
						+ "    discounts {\r\n"
						+ "      details {\r\n"
						+ "        amount {\r\n"
						+ "          amount\r\n"
						+ "          currencyCode\r\n"
						+ "        }\r\n"
						+ "        couponCode\r\n"
						+ "        aliases {\r\n"
						+ "          aliasType\r\n"
						+ "        }\r\n"
						+ "        displayString\r\n"
						+ "      }\r\n"
						+ "    }\r\n"
						+ "    totalPrice {\r\n"
						+ "      value {\r\n"
						+ "        amount\r\n"
						+ "        currencyCode\r\n"
						+ "      }\r\n"
						+ "    }\r\n"
						+ "    payments {\r\n"
						+ "      summary {\r\n"
						+ "        amount {\r\n"
						+ "          amount\r\n"
						+ "        }\r\n"
						+ "        paymentMethodDisplayString\r\n"
						+ "        state\r\n"
						+ "      }\r\n"
						+ "    }\r\n"
						+ "    refunds {\r\n"
						+ "      details {\r\n"
						+ "        id\r\n"
						+ "        aliases {\r\n"
						+ "          aliasType\r\n"
						+ "          aliasId\r\n"
						+ "        }\r\n"
						+ "        updatedAt\r\n"
						+ "        state\r\n"
						+ "        refundRequestReason\r\n"
						+ "        refundTotal {\r\n"
						+ "          totalAmount {\r\n"
						+ "            amount\r\n"
						+ "            currencyCode\r\n"
						+ "          }\r\n"
						+ "        }\r\n"
						+ "        refundFor {\r\n"
						+ "          orderLineItems {\r\n"
						+ "            lineItem {\r\n"
						+ "              id\r\n"
						+ "            }\r\n"
						+ "            amount {\r\n"
						+ "                                unit\r\n"
						+ "                                value\r\n"
						+ "                            }\r\n"
						+ "          }\r\n"
						+ "          causedBy {\r\n"
						+ "              __typename\r\n"
						+ "            id\r\n"
						+ "            state                   \r\n"
						+ "          }\r\n"
						+ "        }\r\n"
						+ "      }\r\n"
						+ "    }\r\n"
						+ "  }\r\n"
						+ "}";
	
	public static final String AMZ_UPDATE_COMPLETE_REFUND_DETAILS ="mutation updateOrder($orderIdentifier: OrderIdentifierInput!, $input: UpdateOrderInput!) {\n"
			+ "    updateOrder(orderIdentifier: $orderIdentifier, input: $input) {\n"
			+ "        order {\n"
			+ "					\n"
			+ "            id\n"
			+ "					orderLinks {\n"
			+ "						destinationType\n"
			+ "						url\n"
			+ "					}\n"
			+ "            aliases {\n"
			+ "                aliasType\n"
			+ "                aliasId\n"
			+ "            }\n"
			+ "            lineItems {\n"
			+ "                id\n"
			+ "                aliases {\n"
			+ "                    aliasType\n"
			+ "                    aliasId\n"
			+ "                }\n"
			+ "                packageInformation {\n"
			+ "                    details {\n"
			+ "                        id\n"
			+ "                        aliases {\n"
			+ "                            aliasType\n"
			+ "                            aliasId\n"
			+ "                        }\n"
			+ "                    }\n"
			+ "                    summary {\n"
			+ "                        state\n"
			+ "                    }\n"
			+ "                }\n"
			+ "                payments {\n"
			+ "                    summary {\n"
			+ "                        amount {\n"
			+ "                            currencyCode\n"
			+ "                            amount\n"
			+ "                        }\n"
			+ "                        paymentMethodDisplayString\n"
			+ "                        state\n"
			+ "                    }\n"
			+ "                    details {\n"
			+ "                        id\n"
			+ "                        amount {\n"
			+ "                            currencyCode\n"
			+ "                            amount\n"
			+ "                        }\n"
			+ "                        paymentMethod {\n"
			+ "                            displayString\n"
			+ "                            type\n"
			+ "                        }\n"
			+ "                        state\n"
			+ "                        payer {\n"
			+ "                            id\n"
			+ "                        }\n"
			+ "                        aliases {\n"
			+ "                            aliasType\n"
			+ "                            aliasId\n"
			+ "                        }\n"
			+ "                        createdAt\n"
			+ "                        updatedAt\n"
			+ "                    }\n"
			+ "                }\n"
			+ "                taxes {\n"
			+ "                    summary {\n"
			+ "                        collectableTaxAmount {\n"
			+ "                            currencyCode\n"
			+ "                            amount\n"
			+ "                        }\n"
			+ "                    }\n"
			+ "                }\n"
			+ "                discounts {\n"
			+ "                    summary {\n"
			+ "                        amount {\n"
			+ "                            currencyCode\n"
			+ "                            amount\n"
			+ "                        }\n"
			+ "                        displayString\n"
			+ "                    }\n"
			+ "                    details {\n"
			+ "                        amount {\n"
			+ "                            currencyCode\n"
			+ "                            amount\n"
			+ "                        }\n"
			+ "                        displayString\n"
			+ "                        aliases {\n"
			+ "                            aliasType\n"
			+ "                            aliasId\n"
			+ "                        }\n"
			+ "                        couponCode\n"
			+ "                    }\n"
			+ "                }\n"
			+ "            }\n"
			+ "            taxes {\n"
			+ "                summary {\n"
			+ "                    collectableTaxAmount {\n"
			+ "                        currencyCode\n"
			+ "                        amount\n"
			+ "                    }\n"
			+ "                }\n"
			+ "            }\n"
			+ "            discounts {\n"
			+ "                summary {\n"
			+ "                    amount {\n"
			+ "                        currencyCode\n"
			+ "                        amount\n"
			+ "                    }\n"
			+ "                    displayString\n"
			+ "                }\n"
			+ "                details {\n"
			+ "                    amount {\n"
			+ "                        currencyCode\n"
			+ "                        amount\n"
			+ "                    }\n"
			+ "                    displayString\n"
			+ "                    aliases {\n"
			+ "                        aliasType\n"
			+ "                        aliasId\n"
			+ "                    }\n"
			+ "                    couponCode\n"
			+ "                }\n"
			+ "            }\n"
			+ "            totalPrice {\n"
			+ "                rollupCharges {\n"
			+ "                    rollupChargeType\n"
			+ "                    displayString\n"
			+ "                    value {\n"
			+ "                        currencyCode\n"
			+ "                        amount\n"
			+ "                    }\n"
			+ "                }\n"
			+ "                value {\n"
			+ "                    currencyCode\n"
			+ "                    amount\n"
			+ "                }\n"
			+ "                verified\n"
			+ "            }\n"
			+ "            payments {\n"
			+ "                summary {\n"
			+ "                    amount {\n"
			+ "                        currencyCode\n"
			+ "                        amount\n"
			+ "                    }\n"
			+ "                    paymentMethodDisplayString\n"
			+ "                    state\n"
			+ "                }\n"
			+ "                details {\n"
			+ "                    id\n"
			+ "                    amount {\n"
			+ "                        currencyCode\n"
			+ "                        amount\n"
			+ "                    }\n"
			+ "                    paymentMethod {\n"
			+ "                        displayString\n"
			+ "                        type\n"
			+ "                    }\n"
			+ "                    state\n"
			+ "                    payer {\n"
			+ "                        id\n"
			+ "                    }\n"
			+ "                    aliases {\n"
			+ "                        aliasType\n"
			+ "                        aliasId\n"
			+ "                    }\n"
			+ "                    createdAt\n"
			+ "                    updatedAt\n"
			+ "                }\n"
			+ "            }\n"
			+ "            refunds {\n"
			+ "                summary {\n"
			+ "                    refundTotal {\n"
			+ "                        totalAmount {\n"
			+ "                            amount\n"
			+ "                            currencyCode\n"
			+ "                        }\n"
			+ "                    }\n"
			+ "                    paymentSummary {\n"
			+ "                        amount {\n"
			+ "                            amount\n"
			+ "                            currencyCode\n"
			+ "                        }\n"
			+ "                        paymentMethodDisplayString\n"
			+ "                        state\n"
			+ "                    }\n"
			+ "                }\n"
			+ "                details {\n"
			+ "                    id\n"
			+ "                    aliases {\n"
			+ "                        aliasType\n"
			+ "                        aliasId\n"
			+ "                    }\n"
			+ "                    createdAt\n"
			+ "                    updatedAt\n"
			+ "                    refundTotal {\n"
			+ "                        totalAmount {\n"
			+ "                            amount\n"
			+ "                            currencyCode\n"
			+ "                        }\n"
			+ "                    }\n"
			+ "                    state\n"
			+ "                    refundFor {\n"
			+ "                        orderLineItems {\n"
			+ "                            lineItem {\n"
			+ "                                id\n"
			+ "                            }\n"
			+ "                            amount {\n"
			+ "                                unit\n"
			+ "                                value\n"
			+ "                            }\n"
			+ "                        }\n"
			+ "                    }\n"
			+ "                    refundRequestReason\n"
			+ "                    refundStatusReason\n"
			+ "                    paymentDetails {\n"
			+ "                        id\n"
			+ "                        amount {\n"
			+ "                            currencyCode\n"
			+ "                            amount\n"
			+ "                        }\n"
			+ "                        paymentMethod {\n"
			+ "                            displayString\n"
			+ "                            type\n"
			+ "                        }\n"
			+ "                        state\n"
			+ "                        payer {\n"
			+ "                            id\n"
			+ "                        }\n"
			+ "                        aliases {\n"
			+ "                            aliasType\n"
			+ "                            aliasId\n"
			+ "                        }\n"
			+ "                        createdAt\n"
			+ "                        updatedAt\n"
			+ "                    }\n"
			+ "                }\n"
			+ "            }\n"
			+ "            returns {\n"
			+ "                details {\n"
			+ "                    id\n"
			+ "                    createdAt\n"
			+ "                    updatedAt\n"
			+ "                    aliases {\n"
			+ "                        aliasType\n"
			+ "                        aliasId\n"
			+ "                    }\n"
			+ "                    state\n"
			+ "                    returnLineItems {\n"
			+ "                        id\n"
			+ "                        returnFor {\n"
			+ "                            orderLineItemAmounts {\n"
			+ "                                amount {\n"
			+ "                                    value\n"
			+ "                                }\n"
			+ "                                lineItem {\n"
			+ "                                    id\n"
			+ "                                    amount {\n"
			+ "                                        value\n"
			+ "                                    }\n"
			+ "                                }\n"
			+ "                            }\n"
			+ "                        }\n"
			+ "                    }\n"
			+ "                }\n"
			+ "            }\n"
			+ "            metadata {\n"
			+ "                executionState\n"
			+ "                createdAt\n"
			+ "                updatedAt\n"
			+ "            }\n"
			+ "            orderLinks {\n"
			+ "                destinationType\n"
			+ "                url\n"
			+ "                displayMessage\n"
			+ "            }\n"
			+ "            packageInformation {\n"
			+ "                details {\n"
			+ "                    id\n"
			+ "                    aliases {\n"
			+ "                        aliasType\n"
			+ "                        aliasId\n"
			+ "                    }\n"
			+ "                }\n"
			+ "                summary {\n"
			+ "                    state\n"
			+ "                }\n"
			+ "            }\n"
			+ "        }\n"
			+ "    }\n"
			+ "}";
	
	public static final String AMZ_ADD_EXTERNAL_REFUND = "mutation updateOrder(\r\n"
			+ "  $orderIdentifier: OrderIdentifierInput!\r\n"
			+ "  $input: UpdateOrderInput!\r\n"
			+ ") {\r\n"
			+ "  updateOrder(orderIdentifier: $orderIdentifier, input: $input) {\r\n"
			+ "    order {\r\n"
			+ "      id\r\n"
			+ "      refunds {\r\n"
			+ "        details {\r\n"
			+ "          id\r\n"
			+ "          aliases {\r\n"
			+ "            aliasId\r\n"
			+ "            aliasType\r\n"
			+ "          }\r\n"
			+ "\r\n"
			+ "          state\r\n"
			+ "        }\r\n"
			+ "      }\r\n"
			+ "    }\r\n"
			+ "  }\r\n"
			+ "}\r\n"
			+ "";
	
	public static final String AMZ_CREATE_EXTERNAL_RETURN = "mutation updateOrder($orderIdentifier: OrderIdentifierInput!, $input: UpdateOrderInput!) {\r\n"
			+ "    updateOrder(orderIdentifier: $orderIdentifier, input: $input) {\r\n"
			+ "    order {\r\n"
			+ "            id    \r\n"
			+ "            returns {\r\n"
			+ "                details {\r\n"
			+ "                    id\r\n"
			+ "                    createdAt\r\n"
			+ "                    updatedAt\r\n"
			+ "                    aliases {\r\n"
			+ "                        aliasType\r\n"
			+ "                        aliasId\r\n"
			+ "                    }\r\n"
			+ "                    state\r\n"
			+ "                    returnLineItems {\r\n"
			+ "                                         \r\n"
			+ "                        id\r\n"
			+ "                        returnFor {\r\n"
			+ "                            \r\n"
			+ "                            orderLineItemAmounts {\r\n"
			+ "                                amount {\r\n"
			+ "                                    value\r\n"
			+ "                                },\r\n"
			+ "                                \r\n"
			+ "                                lineItem {\r\n"
			+ "                                    \r\n"
			+ "                                    id\r\n"
			+ "                                    amount {\r\n"
			+ "                                        value\r\n"
			+ "                                    }\r\n"
			+ "                                }\r\n"
			+ "                            }\r\n"
			+ "                        }\r\n"
			+ "                    }\r\n"
			+ "                }\r\n"
			+ "            }\r\n"
			+ "        }\r\n"
			+ "    }\r\n"
			+ "  }";
}
