yfs.amzConn.AGENT_QCF=BWP_MG_QCF
yfs.amzConn.PROVIDER_URL=file:/opt/ssfs/
yfs.amzConn.fullsync.agentqueue=AMZ.CONN.INV.FULL.SYNC.AGENT.Q
yfs.amzConn.inv.inb.q=AMZ.CONN.INV.INB.Q
yfs.amzConn.order.integqueue=AMZ.CONN.ORDER.INT.Q
yfs.amzConn.fulfillment.integqueue=AMZ.CONN.FULFILLMENT.SYNC.Q
yfs.amzConn.milestones.integqueue=AMZ.CONN.TRACKING.MILESTONE.Q
yfs.amzConn.milestones.purge.agentqueue=AMZ.CONN.TRACKING.PURGE.AGENT.Q
yfs.amzConn.refund.req.integqueue=AMZ.CONN.REFUND.REQ.TO.OMS.INT.Q
yfs.amzConn.sync.ext.return.integqueue=AMZ.CONN.SYNC.EXT.RETURN.TO.AMZ.INT.Q
yfs.amzConn.sync.prime.refund.integqueue=AMZ.CONN.SYNC.PRIME.REFUND.TO.AMZ.INT.Q
yfs.amzConn.return.integqueue=AMZ.CONN.RETURNS.SYNC.TO.OMS.INT.Q

# DEFAULT level properties
yfs.amzConn.bwp_api_client_id.DEFAULT = <YOUR_BWP_API_CLIENT_ID>
yfs.amzConn.bwp_api_client_secret.DEFAULT = <YOUR_BWP_API_CLIENT_SECRET>
yfs.amzConn.bwp_api_oauth_url.DEFAULT = https://api.buywithprime.amazon.com/token
yfs.amzConn.bwp_api_grant_type.DEFAULT = client_credentials
yfs.amzConn.api_time_out.DEFAULT = 10
yfs.amzConn.bwp_api_target_id.DEFAULT = <YOUR_BWP_API_TARGET_ID>
yfs.amzConn.bwp_api_access_key.DEFAULT = <YOUR_BWP_API_ACCESS_KEY>
yfs.amzConn.bwp_api_version.DEFAULT = 2024-11-01
yfs.amzConn.bwp_api_post_url.DEFAULT = https://api.buywithprime.amazon.com/graphql
yfs.amzConn.sp_api_oauth_url.DEFAULT = https://api.amazon.com/auth/o2/token
yfs.amzConn.sp_api_refresh_token.DEFAULT = <YOUR_SP_API_REFRESH_TOKEN>
yfs.amzConn.sp_api_client_id.DEFAULT = <YOUR_SP_API_CLIENT_ID>
yfs.amzConn.sp_api_client_secret.DEFAULT = <YOUR_SP_API_CLIENT_SECRET>
yfs.amzConn.sp_api_grant_type.DEFAULT = refresh_token
yfs.amzConn.GetInventorySummaries.api_url.DEFAULT = https://sandbox.sellingpartnerapi-na.amazon.com/fba/inventory/v1/summaries

# BRAND1 level properties
yfs.amzConn.bwp_api_client_id.BRAND1 = <YOUR_BWP_API_CLIENT_ID>
yfs.amzConn.bwp_api_client_secret.BRAND1 = <YOUR_BWP_API_CLIENT_SECRET>
yfs.amzConn.bwp_api_oauth_url.BRAND1 = https://api.buywithprime.amazon.com/token
yfs.amzConn.bwp_api_grant_type.BRAND1 = client_credentials
yfs.amzConn.api_time_out.BRAND1 = 10
yfs.amzConn.bwp_api_target_id.BRAND1 = <YOUR_BWP_API_TARGET_ID>
yfs.amzConn.bwp_api_access_key.BRAND1 = <YOUR_BWP_API_ACCESS_KEY>
yfs.amzConn.bwp_api_version.BRAND1 = 2024-11-01
yfs.amzConn.bwp_api_post_url.BRAND1 = https://api.buywithprime.amazon.com/graphql
yfs.amzConn.sp_api_oauth_url.BRAND1 = https://api.amazon.com/auth/o2/token
yfs.amzConn.sp_api_refresh_token.BRAND1 = <YOUR_SP_API_REFRESH_TOKEN>
yfs.amzConn.sp_api_client_id.BRAND1 = <YOUR_SP_API_CLIENT_ID>
yfs.amzConn.sp_api_client_secret.BRAND1 = <YOUR_SP_API_CLIENT_SECRET>
yfs.amzConn.sp_api_grant_type.BRAND1 = refresh_token
yfs.amzConn.GetInventorySummaries.api_url.BRAND1 = https://sandbox.sellingpartnerapi-na.amazon.com/fba/inventory/v1/summaries

# BRAND2 level properties
yfs.amzConn.bwp_api_client_id.BRAND2 = <YOUR_BWP_API_CLIENT_ID>
yfs.amzConn.bwp_api_client_secret.BRAND2 = <YOUR_BWP_API_CLIENT_SECRET>
yfs.amzConn.bwp_api_oauth_url.BRAND2 = https://api.buywithprime.amazon.com/token
yfs.amzConn.bwp_api_grant_type.BRAND2 = client_credentials
yfs.amzConn.api_time_out.BRAND2 = 10
yfs.amzConn.bwp_api_target_id.BRAND2 = <YOUR_BWP_API_TARGET_ID>
yfs.amzConn.bwp_api_access_key.BRAND2 = <YOUR_BWP_API_ACCESS_KEY>
yfs.amzConn.bwp_api_version.BRAND2 = 2024-11-01
yfs.amzConn.bwp_api_post_url.BRAND2 = https://api.buywithprime.amazon.com/graphql
yfs.amzConn.sp_api_oauth_url.BRAND2 = https://api.amazon.com/auth/o2/token
yfs.amzConn.sp_api_refresh_token.BRAND2 = <YOUR_SP_API_REFRESH_TOKEN>
yfs.amzConn.sp_api_client_id.BRAND2 = <YOUR_SP_API_CLIENT_ID>
yfs.amzConn.sp_api_client_secret.BRAND2 = <YOUR_SP_API_CLIENT_SECRET>
yfs.amzConn.sp_api_grant_type.BRAND2 = refresh_token
yfs.amzConn.GetInventorySummaries.api_url.BRAND2 = https://sandbox.sellingpartnerapi-na.amazon.com/fba/inventory/v1/summaries
